name: DeepSpectrumLite
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - cudatoolkit=11.0
  - cudnn=8.0
  - pip:
    - click
    - librosa
    - numba
    - pillow
    - pandas
    - scikit-learn
    - tensorflow==2.5.1
    - tensorboard==2.5
    - keras-applications
    - -e .
